refactor: caching fines
esx-framework/esx_policejob pull request #34
Opened 2023-08-09 13:31 UTC by MoskalykA

2023-08-18 18:02 UTC, Gellipapa commented
Hi! @MoskalykA Thank you for pr, but i don't understand what is this. Please describe what you have modified and how to test it.A little more than that "refactor".

2023-08-18 19:43 UTC, MoskalykA commented
Hi, this allows you to make a single SQL query and reduce the number of nets sent. It's a kind of small optimization

2023-08-20 11:41 UTC, CsokiHUN requested changes

2023-08-20 11:41 UTC, CsokiHUN commented on client/main.lua
> +	end
if possible do not use a while loop

```suggestion
if not fineList[category] then
		local p = promise.new()

		ESX.TriggerServerCallback('esx_policejob:getFineList', function(fines)
			p:resolve(fines)
		end, category)

		fineList[category] = Citizen.Await(p)
end
```

2023-08-20 11:42 UTC, CsokiHUN commented on server/main.lua
>  end)
you can load them all into fineList when the script starts

2023-08-20 11:49 UTC, Gellipapa commented
@MoskalykA  Please change default sql files lang to EN. (Replace file)

2023-08-20 11:50 UTC, Gellipapa commented
![image](https://github.com/esx-framework/esx_policejob/assets/22717950/cb219934-2d46-4238-8ae2-57a0c23f33db)

2023-08-20 12:00 UTC, MoskalykA commented on server/main.lua
>  end)
Yes, but that would be one request too many if nobody uses it x)

2023-08-20 12:01 UTC, MoskalykA commented
Good 👍🏻

2023-08-20 16:22 UTC, Gellipapa commented on server/main.lua
>  end)
Hi! I think what @CsokiHUN  means is that then you don't need this callback, but you pre-load the data into a table and work with it and don't start a query to the DB every getFineList.

2023-10-16 21:36 UTC, Gellipapa approved these changes

2023-10-16 21:36 UTC, merged